#!/usr/bin/env bash

export POOTPOOT_APP_DIR=`mktemp -d -t /tmp`
./mkapp poot-poot $POOTPOOT_APP_DIR
rm /tmp/bulkloader.log
rm /tmp/bulkloader.db
rm live_interpretations.data
~/google_appengine/bulkloader.py --dump --log_file=/tmp/bulkloader.log --db_filename=/tmp/bulkloader.db --kind=Interpretation --url=http://poot-poot.appspot.com/remote_api --filename=live_interpretations.data $POOTPOOT_APP_DIR
rm /tmp/bulkloader.log
rm /tmp/bulkloader.db
rm live_comments.data
~/google_appengine/bulkloader.py --dump --log_file=/tmp/bulkloader.log --db_filename=/tmp/bulkloader.db --kind=Comment --url=http://poot-poot.appspot.com/remote_api --filename=live_comments.data $POOTPOOT_APP_DIR
rm -rf $POOTPOOT_APP_DIR
rm *.sql3
