#!/usr/bin/env bash

APP_DIR=`mktemp -d -t /tmp`
./mkapp poot-poot $APP_DIR

## "background job" to propagate changes into built app directory
(while [ -d $APP_DIR ]; do ./mkapp poot-poot $APP_DIR; sleep 1; done) &

## "background job" to bootstrap production data into the local test app
(sleep 3; rm /tmp/bulkloader.db; echo foo | ~/google_appengine/bulkloader.py --log_file=/tmp/bulkloader.log --db_filename=/tmp/bulkloader.db --restore --kind=Interpretation --filename=live_interpretations.data --url=http://localhost:8080/remote_api --app_id=poot-poot --email=j.david.lowe@gmail.com --passin $APP_DIR) &

## start app server...
~/google_appengine/dev_appserver.py --clear_datastore --require_indexes $APP_DIR
rm -rf $APP_DIR
