#!/usr/bin/env bash

jsure -quiet -check poot-poot/static/pootpoot.js

export PYTHONPATH="./poot-poot/:/Users/dlowe/google_appengine/:$PYTHONPATH"
PYLINT='/opt/local/Library/Frameworks/Python.framework/Versions/2.5/bin/pylint -r n'
$PYLINT poot-poot/i
$PYLINT poot-poot/poot
$PYLINT poot-poot/submit
$PYLINT poot-poot/pypoot/interpretation.py

/opt/local/Library/Frameworks/Python.framework/Versions/2.5/bin/nosetests --with-gae --gae-lib-root=/Users/dlowe/google_appengine/ --gae-application=/Users/dlowe/desktop/pootpoot/poot-poot/ ./test_interpretation.py
rm test_interpretation.pyc
