#!/usr/bin/env bash

export PYTHONPATH="./poot-poot/:/Users/dlowe/google_appengine/:$PYTHONPATH"
/opt/local/Library/Frameworks/Python.framework/Versions/2.5/bin/nosetests -q --with-gae --gae-lib-root=/Users/dlowe/google_appengine/ --gae-application=/Users/dlowe/desktop/pootpoot/poot-poot/

rm *.pyc
rm poot-poot/pypoot/*.pyc
