#!/usr/bin/env python

## system
from datetime import datetime

## app engine
from google.appengine.ext import db
from google.appengine.ext import webapp
from google.appengine.api import images
from google.appengine.ext.webapp.util import run_wsgi_app

## this app
from pypoot import interpretation

class Kick(webapp.RequestHandler):
    def get(self):
        i = interpretation.poot({'title_link': 'original-poot'})
        i.content = """
function pootpoot () {
var poot_styles = [
  {one_in: 15, style: "text-decoration:underline"},
  {one_in: 30, style: "text-decoration:line-through"},
  {one_in: 40, style: "text-decoration:blink"},
  {one_in: 10, style: "font-weight:bold"},
  {one_in: 6,  style: "text-transform:uppercase"},
  {one_in: 4,  style: "text-transform:capitalize"},
  {one_in: 11, style: "font-style:italic"},
];

function _pootpoot (target) {
    target.empty();
    target.unbind('click');
    target.click(function () { _pootpoot(target); });
    var line_count = r(1, 40);
    for (var i = 0; i < line_count; ++i) {
        var alignment = ["center", "left", "right"][r(0, 2)];

        var line = '<div style="text-align:' + alignment + ';">';

        var poot_count = r(1, 8);
        for (var j = 0; j < poot_count; ++j) {
            var poot = '<font style="color:' + random_color() + ";font-size:" + ((Math.random() * 2) + 0.2) + "em";
            for (var s in poot_styles) {
                if (r(1, poot_styles[s].one_in) == 1) {
                    poot += ";" + poot_styles[s].style;
                }
            }
            poot += '">';
            if (r(0, 4) == 0) {
                poot += "poot";
            }
            poot += "poot</font>";
            var space_count = r(0, 18);
            for (var k = 0; k < space_count; ++k) {
                poot += "&nbsp;";
            }

            line += poot;
        }
        line += "</div><br/>";
        target.append(line);
    }
    return;
}

return {
    'start': function (target) { _pootpoot(target) },
    'stop':  function () { }
};
}
"""
        i.javascript_hook = 'pootpoot'
        i.put()

        i = interpretation.poot({'title_link': 'wpoot'})
        i.content = """
function wpoot () {
var ADJ_V = ['honest', 'insane', 'emotional', 'empty', 'absent-minded', 'aloof', 'impossible', 'open-minded', 'original', 'underated', 'ugly', 'unequalled'];
var ADJ_C = ['friendly', 'happy', 'true', 'perfect', 'wild', 'lousy', 'foolish', 'stinky', 'radiant', 'weak', 'half-hearted', 'passionate'];
var NOUN_M = ['man', 'boy'];
var NOUN_F = ['woman', 'lady', 'girl'];
var NOUN_U = ['world', 'friend', 'home', 'lie', 'love', 'feeling', 'reaction', 'dollar', 'car', 'ship'];
var PREDICATES = ['is always', 'is never', 'can be', 'cannot be', 'will always seem', 'may never seem', 'is worth', 'is greater than', 'can never be'];

function wpoot_subject () {
    var chunk = r(0, 1) ? 'an ' + ADJ_V[r(0, ADJ_V.length - 1)] : 'a ' + ADJ_C[r(0, ADJ_C.length - 1)];
    chunk = r(0, 3)
        ? chunk + ' '
        : 'a ';

    var choice = r(0, 5);

    if (choice < 2) {
        chunk += NOUN_F[r(0, NOUN_F.length - 1)];
    } else if (choice > 2) {
        chunk += NOUN_U[r(0, NOUN_U.length - 1)];
    } else {
        chunk += NOUN_M[r(0, NOUN_M.length - 1)];
    }

    return chunk;
}

function wpoot_object () {
    var chunk = r(0, 1)
        ? ADJ_V[r(0, ADJ_V.length - 1)]
        : ADJ_C[r(0, ADJ_C.length - 1)];
    chunk = r(0, 1)
        ? chunk
        : wpoot_subject();
    return chunk;
}

function wpoot_predicate () {
    return PREDICATES[r(0, PREDICATES.length - 1)];
}

return {
    'start': function (target) { 
        var wpoot = function (target) {
            target.unbind('click');
            target.click(function () { wpoot(target); });
            target.text(wpoot_subject() + " " + wpoot_predicate() + " " + wpoot_object() + ".");
            target.wrapInner('<h1></h1>');
        };
        wpoot(target);
    },
    'stop': function () { }
};
}
"""
        i.javascript_hook = 'wpoot'
        i.put()

        i = interpretation.poot({'title_link': 'pootris'})
        i.content = """
function play_pootris () {
function _fixposition(X,Y,total_position) {
    var position = total_position;
    if (position == (2 * (X + Y))) {
        position = 0;
    }
    if (position == -1) {
        position = (2 * (X + Y)) - 1;
    }
    return position;
}

function _xy(x,y) {
    return $("#pootris_" + x + '_' + y);
}

function _edge(X,Y,position,c) {
    var x       = 0;
    var y       = 0;
    var drop_x  = 0;
    var drop_y  = 0;
    var delta_x = 0;
    var delta_y = 0;

    if (position < X) {
        x       = position + 1;
        y       = 0;
        drop_x  = x;
        drop_y  = 1;
        delta_y = 1;
        if (c == 'P') {
            delta_x = 1;
        } else if (c == 'O') {
            delta_x = 0;
        } else {
            delta_x = -1;
        }
    } else if (position < (X+Y)) {
        x       = X + 1;
        y       = position - X + 1;
        drop_x  = X;
        drop_y  = y;
        delta_x = -1;
        if (c == 'P') {
            delta_y = 1;
        } else if (c == 'O') {
            delta_y = 0;
        } else {
            delta_y = -1;
        }
    } else if (position < (X+Y+X)) {
        x       = (X + 1) - (position - X - Y + 1);
        y       = Y + 1;
        drop_x  = x;
        drop_y  = Y;
        delta_y = -1;
        if (c == 'P') {
            delta_x = -1;
        } else if (c == 'O') {
            delta_x = 0;
        } else {
            delta_x = 1;
        }
    } else {
        x       = 0;
        y       = (Y + 1) - (position - X - Y - X + 1);
        drop_x  = 1;
        drop_y  = y;
        delta_x = 1;
        if (c == 'P') {
            delta_y = -1;
        } else if (c == 'O') {
            delta_y = 0;
        } else {
            delta_y = 1;
        }
    }

    return {
        'edgebox': _xy(x, y),
        'dropbox': _xy(drop_x, drop_y),
        'drop_x':  drop_x,
        'drop_y':  drop_y,
        'delta_x': delta_x,
        'delta_y': delta_y
    };
}

function _c(string) {
    return string.charAt(r(0,(string.length-1)));
}

function pootris (target, X, Y, string, timeout) {
    var h = '<div id="instructions">';
    h += 'controls: A, S, D<br/>';
    h += 'goal: spell ' + string;
    h += '</div>';
    h += '<table id="pootris_table" cellpadding=0 cellspacing=0>';
    for (var y = 0; y < (Y + 2); ++y) {
        h += '<tr>';
        for (var x = 0; x < (X + 2); ++x) {
            h += '<td id="pootris_' + x + '_' + y + '"/>';
        }
        h += '</tr>';
    }
    h += '</table>';
    h += '<div id="scoreboard">0</div>';
    target.html(h);

    $("#pootris_table").css({'margin':       '0px auto',
                             'border-width': 2,
                             'border-style': 'solid',
                             'color':        '#FFFFFF'});
    for (var y = 0; y < (Y + 2); ++y) {
        for (var x = 0; x < (X + 2); ++x) {
            _xy(x, y).css({
                'width':            12,
                'min-width':        12,
                'max-width':        12,
                'height':           24,
                'min-height':       24,
                'max-height':       24,
                'overflow':         'hidden',
                'text-align':       'center',
                'font-family':      'Impact,sans-serif',
                'color':            '#FFFFFF',
                'background-color': '#000000'
            });
            _xy(x, y).text(' ');
        }
    }
    // inside border...
    _xy(1, 1).css({'border-style': 'dotted none none dotted', 'border-width': 'thin'});
    _xy(1, Y).css({'border-style': 'none none dotted dotted', 'border-width': 'thin'});
    _xy(X, 1).css({'border-style': 'dotted dotted none none', 'border-width': 'thin'});
    _xy(X, Y).css({'border-style': 'none dotted dotted none', 'border-width': 'thin'});
    for (var x = 2; x < X; ++x) {
        _xy(x, 1).css({'border-style': 'dotted none none none', 'border-width': 'thin'});
        _xy(x, Y).css({'border-style': 'none none dotted none', 'border-width': 'thin'});
    }
    for (var y = 2; y < Y; ++y) {
        _xy(1, y).css({'border-style': 'none none none dotted', 'border-width': 'thin'});
        _xy(X, y).css({'border-style': 'none dotted none none', 'border-width': 'thin'});
    }
    $("#instructions").css({'margin':      '10px auto',
                            'width':       $("#pootris_table").width() + 10,
                            'font-family': 'Impact,sans-serif'});
    $("#scoreboard").css({'margin':           '0px auto',
                          'width':            $("#pootris_table").width() - 20,
                          'height':           24,
                          'font-family':      'Impact,sans-serif',
                          'text-align':       'right',
                          'color':            '#FFFFFF',
                          'background-color': '#000000',
                          'border-width':     2,
                          'border-style':     'solid'});

    var piece = function () {
        var ready    = 1;
        var position = 0;
        var c        = _c(string);
        var edge     = _edge(X,Y,position,c);
        var score    = 0;
        edge.edgebox.text(c);

        return {
            'counterclockwise': function () {
                if (ready) {
                    edge.edgebox.text(' ');
                    position = _fixposition(X,Y,position - 1);
                    edge = _edge(X,Y,position,c);
                    edge.edgebox.text(c);
                }
            },
            'clockwise': function () {
                if (ready) {
                    edge.edgebox.text(' ');
                    position = _fixposition(X,Y,position + 1);
                    edge = _edge(X,Y,position,c);
                    edge.edgebox.text(c);
                }
            },
            'drop': function () {
                if (ready && (edge.dropbox.text() == ' ')) {
                    ready = 0;
                    edge.edgebox.text(' ');

                    // drop piece
                    edge.dropbox.text(c);
                    var dx = edge.delta_x;
                    var dy = edge.delta_y;
                    var x  = edge.drop_x;
                    var y  = edge.drop_y;

                    var animate = function () {
                        if ((x + dx) == (X + 1)) {
                                // bounce off the right wall
                                if (dy == 0) {
                                    dx = 0;
                                    dy = 1;
                                }
                                dx *= -1;
                        } else if ((x + dx) == 0) {
                                // bounce off the left wall
                                if (dy == 0) {
                                    dx = 0;
                                    dy = 1;
                                }
                                dx *= -1;
                        }

                        if ((y + dy) == 0) {
                                // bounce off the ceiling
                                dy *= -1;
                        }

                        if ((_xy(x + dx, y + dy).text() == ' ') && ((y + dy) < (Y + 1))) {
                            // move the piece
                            _xy(x, y).text(' ');
                            x += dx;
                            y += dy;
                            _xy(x, y).text(c);

                            // next!
                            timeout.set(animate);
                        } else {
                            // the piece stopped
                            var clearpoots = function () {
                                var subscore = 1;

                                // remove debris
                                for (var clear_x = 1; clear_x <= X; ++clear_x) {
                                    for (var clear_y = Y; clear_y >= 1; --clear_y) {
                                        while (_xy(clear_x, clear_y).text() == '*') {
                                            for (var drop_y = clear_y; drop_y >= 2; --drop_y) {
                                                _xy(clear_x, drop_y).text(_xy(clear_x, drop_y - 1).text());
                                            }
                                            _xy(clear_x, 1).text(' ');
                                        }
                                    }
                                }
                                
                                // check for new POOT
                                var poot_spots = [];
                                for (var start_x = 1; start_x <= X; ++start_x) {
                                    for (var start_y = 1; start_y <= Y; ++start_y) {
                                        for (var dir_x = -1; dir_x < 2; ++dir_x) {
                                            for (var dir_y = -1; dir_y < 2; ++dir_y) {
                                                var found_poot = 1;
                                                for (var i = 0; i < string.length; ++i) {
                                                    if (string.charAt(i) != _xy(start_x+(i*dir_x), start_y+(i*dir_y)).text()) {
                                                        found_poot = 0;
                                                    }
                                                }
                                                if (found_poot) {
                                                    for (var i = 0; i < string.length; ++i) {
                                                        poot_spots.push([start_x+(i*dir_x), start_y+(i*dir_y)]);
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                                if (poot_spots.length) {
                                    for (var i = 0; i < poot_spots.length; ++i) {
                                        subscore *= 2;
                                        _xy(poot_spots[i][0], poot_spots[i][1]).text('*');
                                    }
                                    score = score + subscore;
                                    $("#scoreboard").text(score);
                                    timeout.set(clearpoots);
                                } else {
                                    score = score + subscore;
                                    $("#scoreboard").text(score);

                                    // check for game over
                                    var game_over = 1;
                                    for (var cx = 0; cx < X; ++cx) {
                                        if (_xy(cx + 1, 1).text() == ' ') {
                                            game_over = 0;
                                        }
                                        if (_xy(cx + 1, Y).text() == ' ') {
                                            game_over = 0;
                                        }
                                    }
                                    for (var cy = 0; cy < Y; ++cy) {
                                        if (_xy(1, cy + 1).text() == ' ') {
                                            game_over = 0;
                                        }
                                        if (_xy(X, cy + 1).text() == ' ') {
                                            game_over = 0;
                                        }
                                    }
                                    if (! game_over) {
                                        // next piece!
                                        position = 0;
                                        c        = _c(string);
                                        edge     = _edge(X,Y,position,c);
                                        edge.edgebox.text(c);
                                        ready = 1;
                                    } else {
                                        var go  = "GAME OVER";
                                        var gox = Math.floor((X - go.length) / 2);
                                        var goy = Math.floor(Y / 2);
                                        for (var n = 0; n < go.length; ++n) {
                                            var s = _xy(gox + n + 1, goy);
                                            s.text(go.charAt(n));
                                            s.css({'color': '#FF0000'});
                                        }
                                    }
                                }
                            };
                            clearpoots();
                        }
                    };
                    timeout.set(animate);
                }
            }
        }
    }();

    shortcut.add('A',  piece.counterclockwise, {'type': 'keypress'});
    shortcut.add('S', piece.clockwise, {'type': 'keypress'});
    shortcut.add('D', piece.drop);
}

var timeout_id = null;
var timeout = {
    'set': function (f) {
        timeout_id = setTimeout(f, 40);
    },
    'clear': function () {
        clearTimeout(timeout_id);
    }
};

return {
    'start': function (target) { pootris(target, 15, 12, "POOT", timeout) },
    'stop':  function () {
        timeout.clear();
        shortcut.remove('A');
        shortcut.remove('S');
        shortcut.remove('D');
    }
};
}
"""
        i.javascript_hook = 'play_pootris'
        i.put()

        i = interpretation.poot({'title_link': 'find-poot'})
        i.content = """
function find_poot_classic () {
function _css_box(target) {
    target.css({ 'width':        100,
                 'min-width':    100,
                 'max-width':    100,
                 'overflow':     'hidden',
                 'text-align':   'center',
                 'border-width': 'medium',
                 'border-style': 'solid',
                 'border-color': 'blue',
                 'font-size':    '2.2em',
                 'font-family':  'Impact,sans-serif',
                 'font-weight':  'bold',
                 'background-color': '#000000' });
}

function _find_poot(target, rows, columns, level, message, interval) {
    var remaining_time = 10;

    var splash_html = '<div id="find_poot_splash" style="display:none"><h1>' + message + '</h1><h2>Find the yellow Poot in less than 10 seconds!</h2><h2>To start the game press the yellow Poot</h2><table id="find_poot_splash_table" cellpadding=1 cellspacing=1><tr><td id="green_poot"/><td id="yellow_boot"/><td id="yellow_poot"/></tr></table></div>';
    var table_html = '<div id="find_poot" style="display:none"><table id="find_poot_table" height="304" cellpadding=1 cellspacing=1>';
    for (var row = 0; row < rows; row++) {
        table_html += '<tr>';
        for (var col = 0; col < columns; col++) {
            table_html += '<td id="find_poot_' + row + '_' + col + '"/>';
        }
        table_html += '</tr>';
    }
    table_html += '</table>';
    table_html += '<table id="timer" width=600 height=15 cellpadding=1 cellspacing=1 border=2><tr>';
    for (var t = remaining_time; t > 0; t--) {
        table_html += '<td id="timerbox_' + t + '"/>';
    }
    table_html += '</tr></table>';
    table_html += '</div>';
    target.html(splash_html + table_html);

    poot_row = r(0, rows-1);
    poot_col = r(0, columns-1);

    // set up the splash...
    $("#find_poot_splash").css({'margin':     '0px auto',
                                'width':      '500px'});
    $("#find_poot_splash_table").css({'background-color': '#000000',
                                      'margin':           '0px auto'});
    _css_box($("#green_poot"));
    $("#green_poot").css('color', 'green');
    $("#green_poot").text('Poot');
    _css_box($("#yellow_boot"));
    $("#yellow_boot").css('color', 'yellow');
    $("#yellow_boot").text('Boot');
    _css_box($("#yellow_poot"));
    $("#yellow_poot").css('color', 'yellow');
    $("#yellow_poot").text('Poot');
    $("#yellow_poot").click(function () {
        // hide splash and show game
        $("#find_poot_splash").hide();
        // start the timer
        $("#timer").css('background-color', 'black');
        $("#timer").css('margin', 'auto');
        for (var t = remaining_time; t > 0; t--) {
            var selector = "#timerbox_" + t;
            var box = $(selector);

            box.css({'background-color': 'black'});
        }
        $("#find_poot").show();
        interval.set(function () {
            --remaining_time;
            $("#timerbox_" + (remaining_time + 1)).css('background-color', 'yellow');
            if (remaining_time == 0) {
                interval.clear();
                $("#find_poot").hide();
                _find_poot(target, rows, columns, level, "Time's up!! Try again!", interval);
            }
        }, 1000);
    });

    // set up the game
    $("#find_poot_table").css({'background-color': '#000000',
                               'margin':           '0px auto'});
    for (var row = 0; row < rows; row++) {
        for (var col = 0; col < columns; col++) {
            var selector = "#find_poot_" + row + "_" + col;
            var t = $(selector);

            t.mouseover(function(r_row,r_col,r_t) {
                return function () {
                    if ((r_row == poot_row) && (r_col == poot_col)) {
                        r_t.css('color', 'yellow');
                        r_t.text('Poot');
                    } else {
                        r_t.css('color', 'yellow');
                        r_t.text('Boot');
                    }
                }
            }(row, col, t));

            t.mouseout(function(r_row, r_col, r_t) {
                return function () {
                    r_t.css('color', 'green');
                    r_t.text('Poot');
                }
            }(row, col, t));

            t.click(function(r_row, r_col, r_t) {
                return function () {
                    if ((r_row == poot_row) && (r_col == poot_col)) {
                        interval.clear();
                        $("#find_poot").hide();
                        _find_poot(target, rows, columns, level + 1, "Nice! Try Level " + (level + 1), interval);
                    } else {
                        interval.clear();
                        $("#find_poot").hide();
                        _find_poot(target, rows, columns, level, "That was Boot!! Try again!", interval);
                    }
                }
            }(row, col, t));

            _css_box(t);
            t.css('color', 'green');
            t.text('Poot');
        }
    }
    $("#find_poot_splash").show();
}

var interval_id = null;
var interval = {
    'set': function (f, t) {
        interval_id = setInterval(f, t);
    },
    'clear': function () {
        clearInterval(interval_id);
    }
};

return {
    'start': function (target) { _find_poot(target, 4, 5, 1, 'Level 1', interval) },
    'stop':  function () { interval.clear() },
};
}
"""
        i.javascript_hook = 'find_poot_classic'
        i.put()

APPLICATION = webapp.WSGIApplication([('/_kick', Kick)], debug=True)

def main():
    run_wsgi_app(APPLICATION)

if __name__ == "__main__":
    main()
