#!/usr/bin/env python

## system
from datetime import datetime

## app engine
from google.appengine.ext import db
from google.appengine.ext import webapp
from google.appengine.ext.webapp.util import run_wsgi_app

## this app
from pypoot import interpretation

class Kick(webapp.RequestHandler):
    def get(self):
        query = db.GqlQuery('SELECT * FROM Interpretation')
        for i in query:
            i.title_link = interpretation._make_title_link(i.title)
            self.response.out.write(i.title + " " + i.title_link)
            i.put()

APPLICATION = webapp.WSGIApplication([('/_kick', Kick)], debug=True)

def main():
    run_wsgi_app(APPLICATION)

if __name__ == "__main__":
    main()
