application: poot-poot
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/new-interpretation
  script: queue_handlers/new_interpretation.py
  login: admin

- url: /feeds/interpretations/.*
  script: feeds/interpretations.py

- url: /(poot|list|list_pages|count|submit|approve|disapprove)
  script: api/interpretation.py

- url: /(comment_list|comment_submit)
  script: api/comment.py

- url: /i/([^/]+)
  script: api/i.py

- url: /pootify
  script: pootify.py

- url: /
  static_files: static/interpretation.html
  upload: static/interpretation.html

- url: /interpretation/.*
  static_files: static/interpretation.html
  upload: static/interpretation.html

- url: /list_interpretations/.*
  static_files: static/list_interpretations.html
  upload: static/list_interpretations.html

- url: /(.*)\.(html|js|css|png|ico|txt|jpg)
  static_files: static/\1.\2
  upload: static/.*
