application: poot-poot
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(.*)\.(html|js|css|png|ico)
  static_files: static/\1.\2
  upload: static/.*

- url: /poot
  script: poot

- url: /i/([^/]+)
  script: i

- url: /interpretation/([^/]+)
  static_files: static/index.html
  upload: static/index.html

- url: /submit
  script: submit
