#!/usr/bin/env python
"""fetch metadata describing a single random interpretation"""

import random
import logging
from google.appengine.ext import db

class Interpretation(db.Model):
    is_active    = db.BooleanProperty(required=True)
    type         = db.StringProperty(required=True, choices=set(['image', 'javascript', 'text']))
    content_type = db.StringProperty(required=True)
    content      = db.BlobProperty(required=True)

def main():
    """mock interpretation selector"""
    query = db.GqlQuery("SELECT __key__ FROM Interpretation WHERE is_active = TRUE")
    keys = query.fetch(1000)
    key = random.choice(keys)
    interpretation = db.get(key)
    print """Content-Type: text/plain

{
 "id": %(id)d,
 "type": "%(type)s",
 "location": "/i/%(id)d"
}
""" % {'id': key.id(), 'type': interpretation.type }

if __name__ == "__main__":
    main()
