#!/usr/bin/env python

import random

INTERPRETATIONS = [
    {'id': 0, 'type': "javascript"},
    {'id': 1, 'type': "text"},
]

def main():
    i = random.choice(INTERPRETATIONS)
    print """Content-Type: text/plain

{
 "id": %(id)d,
 "type": "%(type)s",
 "location": "/i/%(id)d"
}
""" % i

if __name__ == "__main__":
  main()
