#!/usr/bin/env python
"""store a new interpretation"""

import logging
from google.appengine.ext import db
from google.appengine.ext import webapp
from google.appengine.ext.webapp.util import run_wsgi_app

from pypoot import interpretation

class Submit(webapp.RequestHandler):
    def get(self):
        self.response.out.write("""
      <html>
        <body>
          <form action="/submit" method="post" enctype="multipart/form-data">
            <div>title: <input type="text" name="title"/></div>
            <div>type: <input type="text" name="type"/></div>
            <div>content-type: <input type="text" name="content_type"></div>
            <div>content: <input type="file" name="content"></div>
            <div><input type="submit" value="poot"></div>
          </form>
        </body>
      </html>""")

    def post(self):
        i = interpretation.Interpretation(
            is_active=True,
            title=self.request.get('title'),
            type=self.request.get('type'),
            content_type=self.request.get('content_type'),
            content=self.request.get('content'))
        i.put()
        self.redirect("/interpretation/%(key)s" % {"key": i.key()})

application = webapp.WSGIApplication([('/submit', Submit)], debug=True)

def main():
    run_wsgi_app(application)

if __name__ == "__main__":
    main()
